QT.serviceframework_private.VERSION = 5.3.0
QT.serviceframework_private.MAJOR_VERSION = 5
QT.serviceframework_private.MINOR_VERSION = 3
QT.serviceframework_private.PATCH_VERSION = 0
QT.serviceframework_private.name = QtServiceFramework
QT.serviceframework_private.libs = $$QT_MODULE_LIB_BASE
QT.serviceframework_private.includes = $$QT_MODULE_INCLUDE_BASE/QtServiceFramework/5.3.0 $$QT_MODULE_INCLUDE_BASE/QtServiceFramework/5.3.0/QtServiceFramework
QT.serviceframework_private.depends = serviceframework dbus network sql
QT.serviceframework_private.module_config = internal_module no_link
