QT.systeminfo_private.VERSION = 5.3.0
QT.systeminfo_private.MAJOR_VERSION = 5
QT.systeminfo_private.MINOR_VERSION = 3
QT.systeminfo_private.PATCH_VERSION = 0
QT.systeminfo_private.name = QtSystemInfo
QT.systeminfo_private.libs = $$QT_MODULE_LIB_BASE
QT.systeminfo_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSystemInfo/5.3.0 $$QT_MODULE_INCLUDE_BASE/QtSystemInfo/5.3.0/QtSystemInfo
QT.systeminfo_private.depends = systeminfo
QT.systeminfo_private.module_config = internal_module no_link
