QT.publishsubscribe_private.VERSION = 5.3.0
QT.publishsubscribe_private.MAJOR_VERSION = 5
QT.publishsubscribe_private.MINOR_VERSION = 3
QT.publishsubscribe_private.PATCH_VERSION = 0
QT.publishsubscribe_private.name = QtPublishSubscribe
QT.publishsubscribe_private.libs = $$QT_MODULE_LIB_BASE
QT.publishsubscribe_private.includes = $$QT_MODULE_INCLUDE_BASE/QtPublishSubscribe/5.3.0 $$QT_MODULE_INCLUDE_BASE/QtPublishSubscribe/5.3.0/QtPublishSubscribe
QT.publishsubscribe_private.depends = publishsubscribe
QT.publishsubscribe_private.module_config = internal_module no_link
