QT.3d_private.VERSION = 5.3.0
QT.3d_private.MAJOR_VERSION = 5
QT.3d_private.MINOR_VERSION = 3
QT.3d_private.PATCH_VERSION = 0
QT.3d_private.name = Qt3D
QT.3d_private.libs = $$QT_MODULE_LIB_BASE
QT.3d_private.includes = $$QT_MODULE_INCLUDE_BASE/Qt3D/5.3.0 $$QT_MODULE_INCLUDE_BASE/Qt3D/5.3.0/Qt3D
QT.3d_private.depends = 3d
QT.3d_private.module_config = internal_module no_link
